name: Generate terraform docs

on:
  push:
    # don't run when we push a tag
    tags-ignore:
      - "*"
    # don't run when we merge to main
    # the action should have run already
    branches-ignore:
      - "main"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "1.8.5"
      - uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33
        name: Setup TFLint
        with:
          tflint_version: v0.38.1
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd
        # pre-commit fails if it changed files
        # we want to go on
        continue-on-error: true
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5
        with:
          default_author: github_actions
